export enum Techs {
    React = "React",
    Angular = "Angular",
    JavaScript = "JavaScript",
    TypeScript = "Typescript",
    HTML = "HTML",
    CSS = "CSS",
    NodeJS = "Node.js",
    ExpressJS = "Express.js",
    Python = "Python",
    Django = "Django",
    Java = "Java",
    Kotlin = "Kotlin",
    MySQL = "MySQL",
    MongoDB = "MongoDB",
    Firebase = "Firebase",
    Hadoop = "Hadoop",
    Spark = "Spark",
    ML = "ML",
    Git = "Git"
}
